on:
  schedule:
    # runs every day at 7:00 AM UTC = 3AM ET in jan, feb, aug-dec
    - cron:  '0 7 * 1,2,8-12 *'
  workflow_dispatch:

name: Update Data

jobs:
  update:
    name: update data
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install necessary packages
        run: |
          install.packages(c("nflreadr", "nflfastR", "gsisdecoder", "readr"), type = "binary")
        shell: Rscript {0}
      - name: Run lat rec update script
        run: Rscript -e 'source("R/update_lat_rec.R")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data
          git commit -m "Lateral data updated `date`" || echo "No changes to commit"
          git push || echo "No changes to commit"