on:
  schedule:
    # runs every day at 7:00 AM UTC = 3AM ET in jan, feb, aug-dec
    - cron:  '0 7 * 1,2,8-12 *'
  workflow_dispatch:

name: Update Multiple Laterals Data

jobs:
  update:
    name: Update Multiple Laterals Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            nflverse/nflreadr, 
            nflverse/nflfastR, 
            nflverse/gsisdecoder, 
            readr
          
      - name: Run lat rec update script
        run: Rscript -e 'source("R/update_multiple_laterals.R")'
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data
          git commit -m "Lateral data updated `date`" || echo "No changes to commit"
          git push || echo "No changes to commit"